version: '3'
services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/dumps
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=128kB"
      - "-c"
      - "effective_cache_size=8kB"